### ISSUE TITLE
implement getconicdual

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/SCS.jl#10]

**Comment by karanveerm** [comment]
@madeleineudell and everyone else who actually understands duals (aka not me)
Consider a constraint
`x == symmetric_semidefinite(n)`
(I'm saying symmetric_semidefinite for clarity)
let the dual of this constraint be an `n x n` vector  `y`

For SCS, we do
```
x == assymetric_semidefinite(n)
x[i, j] == x[j, i] for i != j

```
SCS will return me `n x n` duals for the first constraint and `n * (n - 1) /2` duals for the second constraint. How do I get construct the wanted dual `y` from this?

**Comment by madeleineudell** [comment]
This was resolved some time back, and the ambiguity was obsoleted by the change to lower triangular form.
