### ISSUE TITLE
Building problem on cluster

### ISSUE THREAD

**Issue by jzazo** [JuliaOpt/SCS.jl#117]
I am trying to add SCS to a cluster machine with julia v1.0.0, however I get the following error after trying to build or use it:
```
Building SCS → `~/.julia/packages/SCS/LBz0o/deps/build.log`
┌ Error: Error building `SCS`: 
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ ERROR: LoadError: LibraryProduct(nothing, ["libscsindir"], :indirect, "Prefix(/n/home02/jzazo/.julia/packages/SCS/LBz0o/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] #write_deps_file#152(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /n/home02/jzazo/.julia/packages/BinaryProvider/1nGWd/src/Products.jl:408
│  [3] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{LibraryProduct,1}) at ./none:0
│  [4] top-level scope at none:0
│  [5] include at ./boot.jl:317 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1038
│  [7] include(::Module, ::String) at ./sysimg.jl:29
│  [8] include(::String) at ./client.jl:388
│  [9] top-level scope at none:0
│ in expression starting at /n/home02/jzazo/.julia/packages/SCS/LBz0o/deps/build.jl:55
└ @ Pkg.Operations /builds/pedmon/helmod/rpmbuild/BUILD/julia/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068
```

I think it may be an OpenBlas library problem. I have tried loading different OpenBlas modules but without success. All modules were built using HASWELL target architecture, for CentOS 7. OpenBlas module required either gcc/7.1.0 or intel/17.0.4 modules (I am not sure what the second one loads, maybe something related to MKL), but these two modules are exclusive.

There was a discussion about `openblas` vs `openblas64` [here](https://github.com/JuliaOpt/SCS.jl/issues/58#issuecomment-241874813), and I managed to install SCS with julia v0.6.3 in the cluster following those instructions, but these don't work for me with julia v1.0.0. Any idea of what I could do to build it? May it be a 32 or 64 bit architecture problem of SCS and the modules I am using? I have no problems in my local machine. Thanks.

**Comment by blegat** [comment]
You have followed [these instructions](https://github.com/JuliaOpt/SCS.jl#custom-installation) but they don't work on Julia v1.0 ? They should work on Julia v1.0 so the easiest is maybe to fix that. What didn't work exactly ?

**Comment by jzazo** [comment]
Thank you, I think you pointed me in the right direction because I wasn't trying custom installation, but I still couldn't make it work. I think I need custom ones because the cluster will have a custom build, and not official julia binaries.

I did the following:
```
$ git clone https://github.com/JuliaOpt/SCS.jl.git
$ cd scs
$ make DLONG=1
$ julia
julia> ENV["JULIA_SCS_LIBRARY_PATH"]="/n/home02/jzazo/scs"
julia> ]
(v1.0) pkg> add SCS
```
and after that I get this new error:
```
Building SCS → `~/.julia/packages/SCS/LBz0o/deps/build.log`
┌ Error: Error building `SCS`: 
│ ERROR: LoadError: Could not install custom libraries from /n/home02/jzazo/scs.
│ To fall back to BinaryProvider call delete!(ENV,"JULIA_SCS_LIBRARY_PATH") and run build again.
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /n/home02/jzazo/.julia/packages/SCS/LBz0o/deps/build.jl:35
│  [3] include at ./boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1038
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:388
│  [7] top-level scope at none:0
│ in expression starting at /n/home02/jzazo/.julia/packages/SCS/LBz0o/deps/build.jl:29
└ @ Pkg.Operations /builds/pedmon/helmod/rpmbuild/BUILD/julia/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068
```
I didn't get any error with make command. What did I do wrong?

**Comment by blegat** [comment]
What is `$ ls /n/home02/jzazo/scs/out` ? Try `ENV["JULIA_SCS_LIBRARY_PATH"]="/n/home02/jzazo/scs/out"`

**Comment by jzazo** [comment]
Changing the exported path worked, thank you very much. I guess the path is not completely clear from the install instructions, maybe it can be clarified. Anyway, thanks again for your help.
```
$ ls /n/home02/jzazo/scs/out
demo_socp_direct    libscsdir.a   libscsindir.a
demo_socp_indirect  libscsdir.so  libscsindir.so
```
