### ISSUE TITLE
Helpful error instead of segfault for empty model

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/SCS.jl#122]
With an empty model, SCS segfaults. Instead it should throw an helpful error.
See https://github.com/JuliaOpt/JuMP.jl/issues/1502

**Comment by kalmarek** [comment]
is a test that `n>0` (e.g. in https://github.com/JuliaOpt/SCS.jl/blob/master/src/c_wrapper.jl#L39) sufficient?

**Comment by blegat** [comment]
Yes, and also check that `m` is greater than zero.
