### ISSUE TITLE
copy_to leads to MethodError load_constraint

### ISSUE THREAD

**Issue by kalmarek** [JuliaOpt/SCS.jl#145]
I'm using a very simple script to load the problem:
```julia
using MathOptInterface
MOI = MathOptInterface
using MathOptFormat
using SCS

mof_model = MathOptFormat.CBF.Model();
@time MOI.read_from_file(mof_model, "AutF5.cbf.gz")

let m = SCS.Optimizer(linear_solver=SCS.Direct, eps=1e-10, max_iters=500)
	@time MOI.copy_to(m, mof_model, copy_names=false);
	@info "Optimizing"
	MOI.optimize!(m)
end
```
This works on `0.5.1` but fails on `master` in `MOI.copy_to(m, mof_model, copy_names=false)` with
`ERROR: MethodError: no method matching load_constraint(::SCS.Optimizer, ::MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables,MathOptInterface.Nonnegatives}, ::MathOptInterface.VectorOfVariables, ::MathOptInterface.Nonnegatives)`

@blegat could You have a look at this?

**Comment by blegat** [comment]
SCS does not support `VectorOfVariables`-in-`S` constraint they should be bridged.
You need to use bridged and then a cache for the bridged model like done in the tests.

**Comment by kalmarek** [comment]
Thanks for the quick fix; 
I tried to locate bridge in the tests but I found only one instance in `test/MOI_wrapper.jl` which I can not parse. I tried to look into MOI docs, but found only one short paragraph about bridges: http://www.juliaopt.org/MathOptInterface.jl/stable/apimanual/#Constraint-bridges-1

could You share more light on how to use this? I guess I will need to get acquainted with MOI internals (rather sooner than later), but the documentation is still lacking...

But the question remains: why did it work previously?

**Comment by kalmarek** [comment]
I've come up with the following:
```julia

using MathOptInterface
using MathOptFormat
const MOI = MathOptInterface
const MOIU = MOI.Utilities
const MOIB = MOI.Bridges
using SCS

mof_model = MathOptFormat.CBF.Model();
MOI.read_from_file(mof_model, "AutF5.cbf.gz")

let optimizer = SCS.Optimizer(linear_solver=SCS.Direct, eps=1e-10, max_iters=iters,
    acceleration_lookback=accel)
	MOIU.@model(SCSModelData,
	            (),
	            (MOI.EqualTo, MOI.GreaterThan, MOI.LessThan),
	            (MOI.Zeros, MOI.Nonnegatives, MOI.Nonpositives, MOI.SecondOrderCone,
	             MOI.ExponentialCone, MOI.PositiveSemidefiniteConeTriangle),
	            (), (), (), (), (MOI.VectorAffineFunction,))

	cached_optimizer = MOIU.CachingOptimizer(SCSModelData{Float64}(), optimizer)
	bridged_optimizer = MOIB.full_bridge_optimizer(cached_optimizer, Float64)

	@time MOI.copy_to(bridged_optimizer, mof_model);

	@info "Optimizing"
	MOI.optimize!(bridged_optimizer)
end
```
which even seems to work, but I feel I'm casting spells rather than writing code at the moment :)

what does this `MOIU.@model` macro it do?

**Comment by mlubin** [comment]
> But the question remains: why did it work previously?

SCS doesn't natively support constraints of the type `VectorOfVariables-in-S` for any cone `S`. Previously the SCS MOI wrapper had some ad-hoc code to make this work. This transformation was moved to the bridges and out of the SCS wrapper so that other solvers can re-use the transformation if it applies.
