### ISSUE TITLE
Release SCS as a package

### ISSUE THREAD

**Issue by jennyhong** [JuliaOpt/SCS.jl#15]
It seems like changing MathProgBase's conicinterface for SDPs and getting the new SDP format working will take some time. 

In the meanwhile, can we release SCS as a package? It seems like SCS is working pretty well except dual values for SDPs if the other branches are merged in. This would be useful since a few students might start using this for EE 364A and they'd need exponential cones and SDPs (although I don't think we use dual values for SDPs in any assignment).

**Comment by mlubin** [comment]
No objection here, the package is already useful and we have binaries set up for Windows and OS X.
The README needs some updates though to document the state of the MPB interface and how to use it through Convex.jl (and JuMP).

**Comment by karanveerm** [comment]
Sounds good, I'll start merging in the branches and updating the README.
