### ISSUE TITLE
Apparent bug from Convex#MathOptInterface tests

### ISSUE THREAD

**Issue by ericphanson** [JuliaOpt/SCS.jl#153]
I've been working on updating Convex.jl to use MathOptInterface, and I found that on my branch, SCS fails one test. I think this is likely a bug in SCS's MOI support, because the test passes via MathProgBase and for Mosek with MathOptInterface.

The following test shows the problem (needs `] add https://github.com/ericphanson/Convex.jl#MathOptInterface`).

```julia
using Convex, SCS
using Test, LinearAlgebra
eye(n) = Matrix(1.0I, n, n); TOL = 1e-3

x = [1, 2, 3]
P = Variable(3, 3)
p = minimize(matrixfrac(x, P), P <= 2*eye(3), P >= 0.5 * eye(3))
@test vexity(p) == ConvexVexity()
solve!(p, SCS.Optimizer(verbose=0, eps=1e-6))
@test p.optval ≈ 7 atol=TOL
@test (evaluate(matrixfrac(x, P)))[1] ≈ 7 atol=TOL
```

Here, the second test passes but the first fails (giving about 6 instead).

**Comment by ericphanson** [comment]
Just to say this persists on Convex master (now that the MOI branch has been merged), and with SCS 0.6.3. Also, I was missing a "using LinearAlgebra" in my script above, so I edited it to add that.

**Comment by kalmarek** [comment]
@ericphanson does it still fail for `SCS-v0.6.6`, or master? (it works for me locally)

**Comment by ericphanson** [comment]
No, seems OK on Travis: https://github.com/JuliaOpt/Convex.jl/pull/385. (Getting a strange segfault there in the docs stage but that seems unrelated and the tests pass). Also passes on [ConvexTests](https://ericphanson.github.io/ConvexTests.jl/dev/SCS.html).
