### ISSUE TITLE
failing on 0.4

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/SCS.jl#20]
I fixed build.jl on 0.4 with https://github.com/JuliaOpt/SCS.jl/commit/ea155015f52861b1ba396c271b25be3ab8a47dad, but there seems to be an issue linking to julia's openblas now:

https://travis-ci.org/JuliaOpt/SCS.jl/jobs/55309005#L509

I can reproduce locally. Seem strange because libopenblas.so is exporting ``dsyevr_64_``. Has something changed recently wrt symbol visibility?

@tkelman

**Comment by tkelman** [comment]
Dunno. Might be that the recent ccall changes have broken something. I think you might have the wrong +xxxx number for the Libdl change... Or Jake and I did in our patches for that elsewhere.

**Comment by tkelman** [comment]
Oh, there's yer problem: https://travis-ci.org/JuliaOpt/SCS.jl/jobs/55309005#L374-L375

The `RTLD_` constants aren't exported any more, and since they're being using in `__init__()` the failure was just a warning. I'll fix it in #21.

**Comment by mlubin** [comment]
Fixed by #21
