### ISSUE TITLE
Verbose output with SCS

### ISSUE THREAD

**Issue by SteveDiamond** [JuliaOpt/SCS.jl#27]
Someone contacted me about having trouble getting SCS.jl to print verbose output. They're initializing the solver as ``SCSSolver(verbose=1)`` and constructing the cone program with JuMP. They're not seeing any output.

Any idea how to fix this?

**Comment by IainNZ** [comment]
Weird, according to the README thats the default anyway

**Comment by bodono** [comment]
`SCSSolver(verbose=1)` works for me, and `SCSSolver(verbose=0)` turns it off.

**Comment by madeleineudell** [comment]
@SteveDiamond do you know if this is still a problem?

**Comment by SteveDiamond** [comment]
I'm not sure if it ever worked for the person who contacted me, but they're not using SCS any more.
