### ISSUE TITLE
"unsupported or misplaced expression kw" in high_level_wrapper

### ISSUE THREAD

**Issue by cdetrio** [JuliaOpt/SCS.jl#39]
When trying to run this [convex.jl example](https://github.com/JuliaOpt/Convex.jl/blob/master/examples/max_entropy.ipynb), I get the following error:

>julia> solve!(problem, SCSSolver(Verbose=1))
>ERROR: unsupported or misplaced expression kw
> in create_scs_data at /Users/macbookpro/.julia/v0.3/SCS/src/high_level_wrapper.jl:38
> in create_scs_data at /Users/macbookpro/.julia/v0.3/SCS/src/high_level_wrapper.jl:58
> in SCS_solve at /Users/macbookpro/.julia/v0.3/SCS/src/high_level_wrapper.jl:127
> in SCS_solve at /Users/macbookpro/.julia/v0.3/SCS/src/high_level_wrapper.jl:154
> in optimize! at /Users/macbookpro/.julia/v0.3/SCS/src/SCSSolverInterface.jl:154
> in solve! at /Users/macbookpro/.julia/v0.3/Convex/src/solution.jl:53

Changing [this line](https://github.com/JuliaOpt/SCS.jl/blob/master/src/high_level_wrapper.jl#L38) to `@eval $k = $v` gets it working.

**Comment by mlubin** [comment]
I'm a bit confused about what ``@eval`` is trying to do here. ``@eval`` doesn't run in the local scope:
```
julia> function f()
           k = 1
           @eval k = 2
           @show k
       end

julia> f()
k => 1
```
So I'm surprised that this works at all.
CC @karanveerm

**Comment by mlubin** [comment]
@cdetrio, make sure you have ``SCSSolver(verbose=1)`` not ``SCSSolver(Verbose=1)``.

**Comment by cdetrio** [comment]
thanks, got this error again and Verbose=1 was the problem again!
