### ISSUE TITLE
Rebuild the Windows binaries for new openblas library name

### ISSUE THREAD

**Issue by tkelman** [JuliaOpt/SCS.jl#45]
Ref https://github.com/JuliaLang/julia/pull/13407, putting this here so I don't forget to do it.

**Comment by mlubin** [comment]
Does this mean we need different binaries for 0.4 and master?

**Comment by tkelman** [comment]
0.3 vs newer. RC4 will have the new name if it goes through linux pkgeval cleanly.

**Comment by mlubin** [comment]
It's fine to bump the minimum version on SCS master to ``0.4-rc4`` to make things easier to maintain. I'm more worried that we have no mechanism to automatically update the binaries at all, and we're asking windows users to manually go in an delete files.

**Comment by tkelman** [comment]
Yes, that could be smoother. Maybe via a tag file, like in https://github.com/stevengj/Blosc.jl/blob/master/deps/build.jl ?
