### ISSUE TITLE
support SOCRotated cones

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/SCS.jl#49]
I am trying to solve conic problems involving rotated SOCs and SCS won't take them through MPB conic interface. I see [here that it's on your TODOs](https://github.com/JuliaOpt/SCS.jl/blob/master/src/SCSSolverInterface.jl#L338). Would be great if you could!

**Comment by chriscoey** [comment]
im not actually talking to anyone here

**Comment by bodono** [comment]
A rotated SOC can be easily transformed into a standard SOC, [these slides](http://www.laurentlessard.com/teaching/cs524/slides/12%20-%20cones%20and%20semidefinite%20constraints.pdf
) have the derivation. I'm not sure if it should be in SCS.jl or the higher level package.
