### ISSUE TITLE
indirect solver

### ISSUE THREAD

**Issue by kalmarek** [JuliaOpt/SCS.jl#65]
I see in `build.jl` that only `libscsdir.ext` is built;
Can we have access to the indirect solver method?
(i.e. What needs to be done?)

**Comment by kalmarek** [comment]
I did build `libscsindir` and registered it as `SCS.scsindir`, see (a dirty) 26d51b5e50752d64e31051f5da0c1fd21b6bb1c0
Tests work if I replace all `SCS.scs` by `SCS.scsindir` in `low_level_wrapper.jl`.

So, to have access to indirect solver we could add just a keyword `direct=true` and based on this make ccalls to either `SCS.scs` or `SCS.scsindir`. Is that right?

If so, where to add the keyword? or maybe: make keyword point directly to the lib: `solver_method= SCS.scs|SCS.scsindir` (eyeing `SCS.scsgpu` in the future).

**Comment by mlubin** [comment]
I don't think it's a great idea to be passing around paths to dlls. This is a dispatch issue (deciding which method to call), so we should use Julia's type system as it's designed to be used. You can can pass around dummy types:
```jl
type Direct
end
type Indirect
end

# definition of scs_solve that calls the direct method
function scs_solve(::Type{Direct}, ...)
...
end

# calling scs_solve, may be outside the module
scs_solve(SCS.Direct, ...)
``

**Comment by kalmarek** [comment]
While I understand this might be interpreted as a dispatch issue, wouldn't passing a dummy type lead to code duplication? Functions
```
SCS_init(::Type{Direct}, ...)
SCS_init(::Type{Indirect}, ...)
```
would differ in just one place (1st argument of the `ccall`);
the same is true for `SCS_solve` (the one which actually calls the lib) and `SCS_finish`.
(i.e. `low_level_wrapper.jl` would inflate significantly)

With possible third copy if the Gpu solver is hooked into. Is this the way to go?

**Comment by mlubin** [comment]
This can be accomplished in just a few extra lines of code using ``@eval`` to generate the methods programmatically. The [lapack wrappers in base](https://github.com/JuliaLang/julia/blob/master/base/linalg/lapack.jl) are a good example.

**Comment by kalmarek** [comment]
Ah, I forgot about metaprogramming ;-)

**Comment by kalmarek** [comment]
Please have a look at https://github.com/kalmarek/SCS.jl/tree/indirect
In general I've added keyword `lin_solver`. for value `"direct"` it will dispatch indirect linear solver; everything else will result in direct;

I am particularly not happy about dfc7f541fa40a85e3da31c3c29f23f958a820d0b
(deleting the `:lin_solver` pair from keywords), but I don't really understand what happens in https://github.com/JuliaOpt/SCS.jl/blob/master/src/high_level_wrapper.jl#L37 so I needed to delete it from keywords before passing to `create_scs_data`.

**Comment by bodono** [comment]
"for value "direct" it will dispatch indirect linear solver; everything else will result in the direct solver"
For  value "indirect" presumably?

Anyway, I would recommend making the indirect solver the default, once support for it is added. The reason being that SCS might generally be thought of a solver that can handle problems too big for other solvers, but not necessarily as fast or robust as second-order solvers for small problems. The indirect linear system solver doesn't require factorizing a matrix, an O(n^3) operation, instead it relies only on multiplies, costing O(n^2), so in the regime of problems where SCS could be used the indirect solver starts becoming more efficient. I will leave the decision up to you guys who are doing the work of supporting it though!

**Comment by kalmarek** [comment]
sure,
`lin_solver="indirect"` will result in the indirect solver;
everything else will result in the direct one

**Comment by kalmarek** [comment]
doing some real experiments I noted that SCS called from julia uses only one core, despite `ENV["OMP_NUM_THREADS"] = 4`.

`libscsindir.so` is linked to `libgomp.so`:
```
ldd ./.julia/v0.5/SCS/deps/usr/lib/libscsindir.so
        linux-vdso.so.1 (0x00007fffb5fbc000)
        libmkl_intel_ilp64.so => /opt/intel/compilers_and_libraries_2017.1.132/linux/mkl/lib/intel64_lin/libmkl_intel_ilp64.so (0x00007fae466ff000)
        libmkl_gnu_thread.so => /opt/intel/compilers_and_libraries_2017.1.132/linux/mkl/lib/intel64_lin/libmkl_gnu_thread.so (0x00007fae45523000)
        libmkl_rt.so => /opt/intel/compilers_and_libraries_2017.1.132/linux/mkl/lib/intel64_lin/libmkl_rt.so (0x00007fae44f31000)
        libmkl_core.so => /opt/intel/compilers_and_libraries_2017.1.132/linux/mkl/lib/intel64_lin/libmkl_core.so (0x00007fae4348a000)
        libgomp.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/libgomp.so.1 (0x00007fae4321d000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fae42f1f000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fae42d17000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fae42afa000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fae42761000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fae4255d000)
        /lib64/ld-linux-x86-64.so.2 (0x0000558efbf7b000)
```
(demos in bin folder, build using the same c.ld-flags run on multiple cores)

**Comment by kalmarek** [comment]
Well, I just did some tests and things look strange (both are singe core)
https://gist.github.com/kalmarek/c7b07bdb12afc5309a16c94927da00bf

**Comment by mlubin** [comment]
I'd rather have ``SCSSolver(linearsolver=SCS.Direct)`` than ``SCSSolver(lin_solver="indirect")``. Removes the need to parse strings. If you're going to parse strings, you need to give an error if you see one that's unexpected instead of silently choosing an option.

**Comment by kalmarek** [comment]
That's a good point; 
Passing an unknown linearsolver would result in `MethodError`, so I added informative `ArgumentError`.
Or is `MethodError` descriptive enough?

**Comment by mlubin** [comment]
@kalmarek, up to you. ``MethodError`` doesn't bother me. I was more concerned about silent unintended behavior.

**Comment by kalmarek** [comment]
have a look at it now;
Silent behaviour is gone;
I think `MethodError` is readable enough;

as a side question: should we compile default for multithreaded-enabled lib also for `openblas`? 
(with `-DOPENMP -fopenmp` and `-lgomp`?)

**Comment by mlubin** [comment]
> should we compile default for multithreaded-enabled lib also for ``openblas``?

If you'd like to test it and document it, sure.

**Comment by chriscoey** [comment]
@kalmarek thanks for this - it could be quite useful for us down the track in [Pajarito](https://github.com/JuliaOpt/Pajarito.jl).

Is your branch nearly mergeable?

**Comment by kalmarek** [comment]
I'll try to make it over the weekend;

but be careful -- not all problems are faster with the Indirect solver; mine turned out quite a bit slower. Have a look at the discussion here: https://github.com/cvxgrp/scs/issues/81

**Comment by chriscoey** [comment]
quite interesting! hoping to run some comparisons myself.

what types of cones are in the problems you've been testing? have you tried even larger sized problems?

**Comment by kalmarek** [comment]
Only SDP; The largest problem I tried had `(n,m) ≈ (2e+6, 6e+6)`; but my problems are peculiar as they come from pure mathematics, so may form an isolated case

**Comment by kalmarek** [comment]
@mlubin should I try to rebase/rewrite Indirect solver for the SCS-2.*?

**Comment by bodono** [comment]
Yes! I don't think it should be too difficult since the main API change that SCS 2 introduced was another input argument, which shouldn't affect the direct vs indirect calls.

Generally speaking the indirect solver is better (in some sense) and so it is now the default in all other languages, since it's faster for medium to large problems and it's roughly as robust.

**Comment by kalmarek** [comment]
done in https://github.com/JuliaOpt/SCS.jl/pull/95
