### ISSUE TITLE
ERROR: A->p (column pointers) decreasing

### ISSUE THREAD

**Issue by kalmarek** [JuliaOpt/SCS.jl#74]
I've seen a much older bug with similar message.
This happens on julia-0.5.1 with openblas and SCS/master 
```
SDP_problem = Maximization problem with:
 * 2018882 linear constraints
 * 1 semidefinite constraint
 * 1959211 variables
Solver is default solver
solver = SCS.SCSSolver(Any[(:eps,1.0e-8),(:max_iters,100000),(:verbose,true)])
ERROR: A->p (column pointers) decreasing
invalid linear system input data
ERROR: Validation returned failure
ERROR: SCS_NULL input
```
This is how I generate the problem:
```
function create_SDP_problem(matrix_constraints, Δ, Δ², N)
    @assert length(Δ) == length(matrix_constraints)
    m = JuMP.Model();
    JuMP.@variable(m, A[1:N, 1:N], SDP)
    JuMP.@SDconstraint(m, A >= 0)
    JuMP.@constraint(m, sum(A[i] for i in eachindex(A)) == 0)
    JuMP.@variable(m, κ >= 0.0)
    JuMP.@objective(m, Max, κ)

    for (pairs, δ², δ) in zip(matrix_constraints, Δ².coefficients, Δ.coefficients)
        JuMP.@constraint(m, sum(A[i,j] for (i,j) in pairs) == δ² - κ*δ)
    end
    return m
end
```
I haven't seen this on a much smaller problem generated by the exact same code:
```
SDP_problem = Maximization problem with:
 * 157204 linear constraints
 * 1 semidefinite constraint
 * 156521 variables
```

**Comment by kalmarek** [comment]
Ok, I have an SDP problem in JuMP which builds internal model (`JuMP.build`) , but fails `MathProgBase.optimize!(m.internalModel)` in a non-deterministic fashion. I tried to turn off all Threading and multiprocessing features. Does the issue belong to SCS, or should I report it in JuMP?

**Comment by mlubin** [comment]
Very unlikely to be an issue with JuMP. Try writing the problem to a [CBF file](https://github.com/mlubin/ConicBenchmarkUtilities.jl) and solving again with SCS. You can also try another solver like Mosek or CSDP.

**Comment by kalmarek** [comment]
I've already tried with Mosek: Out of Space; I will try to grasp CBF format tommorrow.

I've just noted (in REPL or Jupyter), that sometimes second/third/fourth call to `optimize!`, or `JuMP.solve` actually manages to start the solver.

**Comment by mlubin** [comment]
There's nothing you need to know about the CBF format, just use the code in that package.

**Comment by kalmarek** [comment]
just noted that

**Comment by kalmarek** [comment]
I tried ConicBenchmarkTools, but I get
```
ConicBenchmarkUtilities.jump_to_cbf(m, "sdptest", "sdptest.cbf")
CBF format does not allow PSD variables to appear in affine expressions defining PSD constraints
```

**Comment by mlubin** [comment]
You can avoid that by replacing ``@variable(m, X[1:N,1:N], SDP)`` with ``@variable(m, X[1:N,1:N]); @SDConstraint(m, X >= 0)``.

**Comment by kalmarek** [comment]
When I save to cbf and load, MathProgBase will start the optimisation as it should;
I also observed, that (for the problematic `m`)
```
JuMP.build(m, ....)
im = m.internal_model
try
    JuMP.solve(m) #->Error
catch
    JuMP.build(m, ...)
    @show im == m.internal_model
    JuMP.solve(m)
end
```
shows `false`, but happily runs the second `JuMP.solve`

**Comment by mlubin** [comment]
You'll probably have to do some intense debugging on SCS to see where the problem data is getting corrupted.

**Comment by kalmarek** [comment]
If I had time I'd gladly learn how to, as that is definitely beyond my programming skills...

**Comment by mlubin** [comment]
This was possibly caused by https://github.com/JuliaOpt/SCS.jl/issues/90
