### ISSUE TITLE
return :Userlimit rather than :UnknownError when hit iteration limit 

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/SCS.jl#79]
@mlubin

**Comment by mlubin** [comment]
https://github.com/JuliaOpt/SCS.jl/pull/66

**Comment by kalmarek** [comment]
I guess this is about MathProgBase, which is deprecated?

MOI status (https://www.juliaopt.org/MathOptInterface.jl/dev/apimanual/#Common-status-situations-1) is returned translated as per https://github.com/JuliaOpt/SCS.jl/blob/b455b04fe33e1455dd40863284e501f0456bd398/src/MOI_wrapper.jl#L466

@chriscoey please reopen if you still need this
