### ISSUE TITLE
Add symmetry constraints for SDP

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/SCS.jl#8]
The MPB interface implicitly assumes that SDP constraints imply symmetry, but SCS needs these as explicit equalities, see discussion here: https://github.com/JuliaOpt/Mosek.jl/issues/29#issuecomment-66731064. These equalities should be introduced in SCS.jl and not by Convex.jl.

**Comment by bodono** [comment]
Is this temporary until we've moved over the symmetric input format for SDPs, or something you want to remain long term?

**Comment by karanveerm** [comment]
This is definitely temporary because it is inefficient and unnecessary. The reason we're doing this is because we want SCS.jl to be released very soon so it can used for EE364A.

We'll be moving over to the new SDP format after [this](https://github.com/JuliaOpt/MathProgBase.jl/issues/51).

**Comment by bodono** [comment]
Ok, makes sense.
