### ISSUE TITLE
critical memory bug

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/SCS.jl#90]
If I'm understanding things correctly [`create_scs_matrix`](https://github.com/JuliaOpt/SCS.jl/blob/d63bc8ca6a8d56ee1ec046589c1f211751482f9a/src/high_level_wrapper.jl#L5) returns pointers to vectors that can be freed by the Julia GC at any point. I'm surprised we haven't seen more segfaults.

@bodono, does SCS make an internal copy of the `A` matrix, or does it assume that the user won't free it before `SCS_solve`?

**Comment by bodono** [comment]
SCS will make an internal copy of the matrix if it is compiled with `COPY_A_MATRIX` true, which it is in SCS.jl according to https://github.com/JuliaOpt/SCS.jl/blob/master/deps/build.jl#L46.

**Comment by mlubin** [comment]
Ok, that's good but still there's a risk of the memory being freed before it gets to SCS. This needs a fix.
