### ISSUE TITLE
Package build fails in julia computing docker

### ISSUE THREAD

**Issue by cgroll** [JuliaOpt/SCS.jl#96]
I tried to install `SCS` in the julia docker container provided here: 
https://hub.docker.com/_/julia/

The command I used to get and start the container was: `docker run -it --rm julia`

Build fails with following error:
![scs_built_errors](https://user-images.githubusercontent.com/2378081/35431616-73bdea8e-027d-11e8-9ec2-f8940ca6917d.png)

I am not familiar with the details. So if the problem is on my side, please ignore and simply close the issue.

**Comment by mlubin** [comment]
I'm guessing the docker container doesn't have a compiler set up? That's currently needed to install SCS on linux.

**Comment by cgroll** [comment]
you were right :+1: installing a compiler within the docker container did solve the problem.

thx a lot!
